app/models.py
from datetime import datetime
from flask_login.mixins import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login


class Users_req(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, nullable=False)
    phone = db.Column(db.String(11), nullable=False)

    date_of_request = db.Column(db.DateTime, default=datetime.utcnow)
    is_active = db.Column(db.Boolean, default=True)

    def __repr__(self):
        return f'Имя: {self.username}'


class Users_base(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


@login.user_loader
def load_user(id):
    return Users_base.query.get(int(id))

app/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    login = StringField("Login", id="login__email", validators=[DataRequired()])
    password = PasswordField("Password", id="login__password", validators=[DataRequired()])
    submit = SubmitField("Submit", id="login__submit")

app/__init__.py
import os

from config import Config, BASEDIR
from flask import Flask, url_for, redirect
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()
login = LoginManager()
migrate = Migrate()


def create_app(configuration=Config):
    print(os.path.join(BASEDIR, 'templates'))
    app = Flask(__name__, template_folder=os.path.join(BASEDIR, 'templates'), static_folder=os.path.join(BASEDIR, 'static'))
    app.config.from_object(configuration)
    
    db.init_app(app)
    login.init_app(app)
    migrate.init_app(app, db)

    from app.admin import bp as admin_bp
    from app.main import bp as main_bp

    app.register_blueprint(admin_bp)
    app.register_blueprint(main_bp)

    @app.route("/")
    def index():
        return redirect(url_for("main.index"))

    return app

app/admin/__init__.py
from flask import Blueprint

bp = Blueprint("admin", __name__, url_prefix='/admin')

from app.admin import routes

app/admin/routes.py
import json
from flask import flash, json, redirect, render_template, url_for, jsonify, request
from flask_login import login_user, login_required, logout_user

from app import db
from app.admin import bp
from app.admin.forms import LoginForm

from app.models import Users_base, Users_req


@login_required
@bp.route('/users_req')
def users_req():
    requests = Users_req.query.filter_by(is_active=True).order_by(Users_req.username).all()
    return render_template('users_req.html', requests=requests)


@login_required
@bp.route("/decline", methods=["POST"])
def decline():
    data = json.loads(request.data)
    request_id = int(data["request_id"])
    user_request = Users_req.query.get(request_id)
    user_request.is_active = False
    db.session.add(user_request)
    db.session.commit()
    return jsonify({"status": "success"})


@bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        username = form.login.data
        password = form.password.data
        print(username)

        user = Users_base.query.filter_by(username=username).first()

        if user is None or not user.check_password(password):
            flash("Неверный логин или пароль")
            redirect(url_for("admin.login"))
        else:
            login_user(user)
            return redirect(url_for("main.index"))
        
    return render_template("login.html", form=form)


@bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index"))

app/main/__init__.py
from os import lseek

from flask import Blueprint

bp = Blueprint("main", __name__, url_prefix='/main')

from app.main import routes

app/main/routes.py
from flask import render_template, redirect, request, flash
from flask.helpers import url_for

from app import db
from app.models import Users_req
from app.main import bp


@bp.route('/')
def index():
    return render_template('index.html')


@bp.route('/about')
def about():
    return render_template('about.html')


@bp.route('/form', methods=['POST', 'GET'])
def form():
    if request.method == "POST":
        username = request.form['username']
        phone = request.form['phone']

        if username == "" or phone == "":
            flash("Произошла ошибка")
            return redirect(url_for("main.form"))
        
        user = Users_req(username=username, phone=phone)

        db.session.add(user)
        db.session.commit()
        flash("Успешно записались, траляля, (app/main/routes.py line 30)")
        return redirect(url_for("main.index"))
    else:
        return render_template('form.html')


@bp.route('/photos')
def photos():
    return render_template('photos.html')


@bp.route('/contacts')
def contacts():
    return render_template('contacts.html')

templates/about.html
{% extends 'base.html' %}

{% block title %}
<title>О нас</title>
{% endblock %}

{% block body %}

<h2>Кто мы и что предлагаем</h2>
<p>
    Наша компания предоставляет услуги по проведению квестов в реальности с 2015 года.
    За это время мы успели провести более 5000 игр, открыть 5 квестов, и провести более 100 различных акций
<br><h1>Почему именно мы?</h1>
<br> Мы являемся единственной компанией в городе, которая не работает по франшизе.
     Иными словами, каждый наш квест был придуман полностью нами
</p>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="ru">
  <head>
      {% block title %} {% endblock %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"/>
  </head>
<body>

  <nav class="navbar navbar-light navbar navbar-expand-lg" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">НА ГРАНИ</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.about') }}">О нас</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.photos') }}">Фото</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.contacts') }}">Контакты</a>
          </li>
          {% if not current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.form') }}">Запись</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('admin.login') }}">Авторизация</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('admin.users_req') }}">Запросы</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('admin.logout') }}">Выход</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
</nav>
<div class="container-alert">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
      {% for message in messages %}
      <div class="alert alert-success" role="alert"><span id="flash-message">{{ message }}</span></div>
      {% endfor %}
  {% endif %}
  {% endwith %}
</div>
{% block body %}{% endblock %}

 <footer class="pt-4 my-md-5 pt-md-5 border-top" style="background-color: #e3f2fd;">
        <div class="row">
            <div class="col-12 col-md">
              <small class="d-block mb-3 text-muted">© 2015–2021</small>
            </div>
            <div class="col-6 col-md">
                <h5>Разделы</h5>
                <ul class="list-unstyled text-small">
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="/">Главная</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="/form">Запись</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Интересное</h5>
                <ul class="list-unstyled text-small">
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="/photos">Фото</a></li>
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="/about">О нас</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <ul class="list-unstyled text-small">
                    <li class="mb-1"><a class="link-secondary text-decoration-none" href="/contacts">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>


  </body>
</html>

templates/contacts.html
{% extends 'base.html' %}

{% block title %}
<title>Контакты</title>
{% endblock %}

{% block body %}

<div class="container mt-3 "></div>
    <h2>Как нас найти</h2>
    <p>Мы находимся по адресу г.Благовещенск Горького 156, тц "Куб", 2 секция
    <br>Вы можете связвться с нами:
        <br> По телефону 340-333
        <br> Через what's upp 8-963-814-03-033
        <br> Через  <a href="https://www.instagram.com/quest_blag/">инстаграмм</a>


    </p>
    <div align="center" style="position:relative;left:15;overflow:hidden;">
        <a href="https://yandex.ru/maps/org/kvesty_na_grani/1701340954/?utm_medium=mapframe&utm_source=maps" style="color:#eee;font-size:12px;position:absolute;top:0px;">Квесты на грани</a>
        <a href="https://yandex.ru/maps/77/blagoveshchensk/category/quests/56396710895/?utm_medium=mapframe&utm_source=maps" style="color:#eee;font-size:12px;position:absolute;top:14px;">Квесты в Благовещенске</a>
        <a href="https://yandex.ru/maps/77/blagoveshchensk/category/children_and_teenagers_clubs/184107202/?utm_medium=mapframe&utm_source=maps" style="color:#eee;font-size:12px;position:absolute;top:28px;">Клуб для детей и подростков в Благовещенске</a>
        <iframe src="https://yandex.ru/map-widget/v1/-/CCUaEHEdTD" width="560" height="400" frameborder="1" allowfullscreen="true"  style="position:relative;"></iframe>
    </div>

{% endblock %}

templates/form.html
{% extends 'base.html' %}

{% block title %}
<title>Запись</title>
{% endblock %}

{% block body %}
<div class="container mt-5">
    <h2>Как забронировать игру</h2>
    <p>Для того, чтобы записаться на квест, оставьте небольшую заявку, мы свяжемся с вами и обсудим ваши желания
    <br>Помните, что чем раньше вы записываетесь, тем больше возможности выбора даты и времени
    </p>
    <form method="post">
        <input type="text" class="form-control" name="username" id="username" placeholder="Введите свое имя"><br>
        <input type="text" class="form-control" name="phone" id="phone"  placeholder="Введите свой номер телефона"><br>

        <button class="btn-success" type="submit">Оставить заявку</button>
    </form>

</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
<title>НА ГРАНИ</title>
{% endblock %}

{% block body %}

        <div class="container pt-px-lg-80">
            <div class="container mt-5">
            <div class="row gx-lg-5">
              <div class="col-lg-6">
                <div class="position-relative">
                    <img class="mb-lg-0 mb-px-30 z-index-2 height-px-456 object-fit-cover w-50" src="/static/images/bunker.jpg" alt="home image-4">
                </div>
              </div>
              <div class="col-lg-6 my-auto">
                <h5 class="font-letter-space mb-px-8">Секретный бункер</h5>
                <h2 class="mb-px-17">Захватывающий квест в жанре экшн</h2>
                <div class="pe-px-lg-90 pb-px-6">
                  <p>Описание квеста.</p>
                </div>
              </div>
            </div>
          </div>

<hr class="featurette-divider">

    <div class="container pt-px-lg-80">
            <div class="row gx-lg-5">
              <div class="col-lg-6 order-lg-2">
                <div class="position-relative">
                    <img class="mb-lg-0 mb-px-30 z-index-2 height-px-500 object-fit-cover w-50 " src="/static/images/giper.jpg" alt="home image-4" >
                </div>
              </div>
              <div class="col-lg-6 order-lg-1">
                <h5 class="font-letter-space mb-px-8">ГИПЕРквест</h5>
                <h2 class="mb-px-17">Нереально сложный и увлекательный</h2>
                <div class="pe-px-lg-90 pb-px-6">
                  <p>Описание квеста</p>
                </div>
              </div>
            </div>
          </div>

    </div>
  </div>

<hr class="featurette-divider">

<div class="container pt-px-lg-80">
            <div class="container mt-5">
            <div class="row gx-lg-5">
              <div class="col-lg-6">
                <div class="position-relative">
                    <img class="mb-lg-0 mb-px-30 z-index-2 height-px-456 object-fit-cover w-50" src="/static/images/prizraki.jpg" alt="home image-4">
                </div>
              </div>
              <div class="col-lg-6 my-auto">
                <h5 class="font-letter-space mb-px-8">Призрак кшмарной хижины</h5>
                <h2 class="mb-px-17">Содрагающий нервы квест в жанре ужасы</h2>
                <div class="pe-px-lg-90 pb-px-6">
                  <p>Описание квеста.</p>
                </div>
              </div>
            </div>
          </div>


{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}
<title>Авторизация</title>
{% endblock %}


{% block body %}
<div class="container mt-5">
<form method="post">
    {{ form.hidden_tag() }}
            
    <div>
        {{ form.login.label }}
        {{ form.login(class_="form-control") }}
        {% for error in form.login.errors %}
            <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        {{ form.password.label }}
        {{ form.password(class_="form-control") }}
        {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </div>
    <div>
        {{ form.submit() }}
    </div>
</form>
</div>
{% endblock %}

templates/photos.html
{% extends 'base.html' %}

{% block title %}
<title>Фото</title>
{% endblock %}

{% block body %}

<div class="album py-5 bg-light">
            <div class="container">

                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="/static/images/giper_3.jpg" class="size-set">
                            <div class="card-body">
                                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <div class="d-flex justify-content-between align-items-center">

                                        <h5>ГИПЕРКВЕСТ</h5>

                                    </div>
                                    <small class="text-muted">Спасительное нечто</small>

                            </div>
                        </div>
                    </div>

                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="/static/images/giper_1.jpg" class="size-set">
                            <div class="card-body">
                                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <h5>ГИПЕРКВЕСТ</h5>
                                </div>
                                <small class="text-muted">Сектор А</small>

                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="/static/images/giper_2.jpg" class="size-set">
                            <div class="card-body">
                                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <div class="d-flex justify-content-between align-items-center">

                                    <h5>ГИПЕРКВЕСТ</h5>

                                </div>
                                <small class="text-muted">Индикатор жизни</small>

                            </div>
                        </div>
                    </div>




                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="/static/images/prizraki_1.jpg" class="size-set">
                            <div class="card-body">
                                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <div class="d-flex justify-content-between align-items-center">

                                    <h5>Призрак кошмарной хижины</h5>

                                </div>
                                <small class="text-muted">Спасительное нечто</small>

                            </div>
                        </div>
                    </div>

                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="/static/images/prizraki_2.jpg" class="size-set">
                            <div class="card-body">
                                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <h5>Призрак кошмарной хижины</h5>
                                </div>
                                <small class="text-muted">Сектор А</small>

                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="/static/images/prizraki_3.jpg" class="size-set">
                            <div class="card-body">
                                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <h5>Призрак кошмарной хижины</h5>
                                </div>
                                <small class="text-muted">Индикатор жизни</small>
                            </div>
                        </div>
                    </div>


                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="/static/images/bunker_1.jpg" class="size-set">
                            <div class="card-body">
                                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <h5>Секретный бункер</h5>
                                </div>
                                <small class="text-muted">Индикатор жизни</small>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="/static/images/bunker_2.jpg" class="size-set">
                            <div class="card-body">
                                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <h5>Секретный бункер</h5>
                                </div>
                                <small class="text-muted">Индикатор жизни</small>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="/static/images/bunker_3.jpg" class="size-set">
                            <div class="card-body">
                                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <h5>Секретный бункер</h5>
                                </div>
                                <small class="text-muted">Индикатор жизни</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <style>
            .size-set {
                max-height: 350px;
            }
        </style>

{% endblock %}

templates/users_req.html
{% extends 'base.html' %}

{% block title %}
<title>Заявки пользователей</title>
{% endblock %}

{% block body %}
<div class="container">

    <div id="user-request-block">
        {% for request in requests %}
        <div class="wrap">
            <div class="user-request" id="{{ request.id }}">
                <div class="user-request__username">
                    Имя: {{ request.username }}
                </div>
                <div class="user-request__phone">
                    Номер телефона: {{ request.phone }}
                </div>
                <div class="user-request__date">
                    Дата заявки: {{ request.date_of_request.day }}:{{ request.date_of_request.month }}:{{ request.date_of_request.year }}
                </div>
            </div>
            <div class="decline">
                <button type="button" class="btn btn-danger">Отклонить</button>
            </div>
        </div>
        {% endfor %}
    </div>


    <!-- <table>
        <tr><th>Имя пользователя</th><th>Номер телефона</th></tr>
        <tr>
        {% for request in requests %}
            <td>{{ request.username }}</td><td>{{ request.phone }}</td>


    {% endfor %}
    </tr></table> -->
</div>


<style>
    #user-request-block {
        width: 80%;
        height: 100%;
        margin-top: 20px;
    }

    .wrap {
        border: 1px solid black;
        margin-bottom: 20px;
    }

    .user-request {
        display: inline-block;
        width: 75%;
        padding: 10px 20px;
    }
    .decline {
        display: inline-block;
        width: 20%;
        height: 100%;
    }
    
    .non-vizible {
        display: none;
    }
</style>

<script>
    let wrap = document.getElementsByClassName("wrap")
    for (let element of wrap) {
        let request = element.getElementsByClassName("user-request")[0]
        let button = element.getElementsByClassName("btn")[0];
        console.log(button)
        let request_id = request.id;
        button.onclick = () => {
            fetch("{{ url_for('admin.decline') }}", {
                method: "POST", 
                body: JSON.stringify({request_id: request_id})
            })
            .then(data => data.json())
            .then(data => {
                if (data.status === "success") {
                    element.classList.add("non-vizible");
                }
            })
        }
    }
</script>
{% endblock %}